# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.releaserc.yml'
      - '.github/workflows/publish.yml'
      - '.github/scripts/prepare.sh'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
          toolchain: nightly # required for readme-generation
          target: x86_64-pc-windows-gnu
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: check
      - name: Publish
        uses: cycjimmy/semantic-release-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits
      - name: Cargo login
        if: steps.release.outputs.new_release_published == 'true'
        run: cargo login ${{ secrets.CARGO_CRATES_IO_TOKEN }}
      - name: Cargo publish
        if: steps.release.outputs.new_release_published == 'true'
        run: cargo publish --target=x86_64-pc-windows-gnu
